language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services:
  - redis-server

before_install: bash build_delayqueue.sh

before_script:
  - composer install

script: vendor/bin/phpunit

notifications:
    on_success: never
    on_failure: always